[versions]
java              = "25"
springBoot        = "3.5.0"
springDependency  = "1.1.7"
archunit          = "1.4.0"
testcontainers    = "2.0.4"
postgresql        = "42.7.10"
junit             = "5.12.2"
assertj           = "3.27.3"
mockito           = "5.23.0"
awaitility        = "4.2.2"

[libraries]
spring-boot-starter             = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-web         = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-data-jpa    = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-actuator    = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-test        = { module = "org.springframework.boot:spring-boot-starter-test" }
postgresql                      = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
archunit-junit5                 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
testcontainers-bom              = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
flyway-core                     = { module = "org.flywaydb:flyway-core" }
flyway-database-postgresql      = { module = "org.flywaydb:flyway-database-postgresql" }
testcontainers-junit            = { module = "org.testcontainers:junit-jupiter" }
testcontainers-postgresql       = { module = "org.testcontainers:postgresql" }
junit-bom                       = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter                   = { module = "org.junit.jupiter:junit-jupiter" }
assertj-core                    = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito-core                    = { module = "org.mockito:mockito-core", version.ref = "mockito" }
awaitility                      = { module = "org.awaitility:awaitility", version.ref = "awaitility" }

[plugins]
spring-boot           = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency     = { id = "io.spring.dependency-management", version.ref = "springDependency" }
